### ISSUE TITLE
Support for additional notifications types? 

### ISSUE THREAD

**Issue by Deanosim** [petersem/monocker#10]
Would it be possible to get support for notifications with gotify?
Gotify is a self hosted alternative to things like pushover.
[https://gotify.net ](https://gotify.net)

Also the ability to send notifications with normal webhooks, Since discord webhooks are not compatible with other software usually.

**Comment by BadCo-NZ** [comment]
> Will look at notify. I though discord was already there?

@petersem Might be worth it to look into supporting Apprise

https://github.com/caronc/apprise

**Comment by GinjNTonic** [comment]
Politely boosting this request.  :)  
Gotify/Apprise would be extremely appreciated by self-hosters.

**Comment by Proximus888** [comment]
Jep, would love ntfy.sh integration. Best is apprise!

**Comment by portalzine** [comment]
Just found this and apprise notification support would be amazing. 
ntfy would be a nice start and simple to integrate; )
Cheers

**Comment by petersem** [comment]
Will investigate

**Comment by petersem** [comment]
@Proximus888 @Nairou NTFY is in the latest build. I still plan to add appraise, however I just havent had a chance to do so yet.

**Comment by Proximus888** [comment]
> @Proximus888 @Nairou NTFY is in the latest build. I still plan to add appraise, however I just havent had a chance to do so yet. 

Thanks, works.

But ```NTFY_USER and NTFY_PASS``` doesn't work for me, I get a 401 error. Authentication error.

My work around was to pass the user and password on through the url. So this worked for me: ```CUSTOM_NTFY_SERVER: 'https://user:password@ntfy.domain.tld'```

Will continue to check if I can get ```NTFY_USER and NTFY_PASS``` to work.

**Comment by petersem** [comment]
@Proximus888 ah bummer. I'll have a look later tonight. Should be a simple fix

**Comment by petersem** [comment]
Appraise will be next, then gotify

**Comment by petersem** [comment]
> > @Proximus888 @Nairou NTFY is in the latest build. I still plan to add appraise, however I just havent had a chance to do so yet.
> 
> Thanks, works.
> 
> But `NTFY_USER and NTFY_PASS` doesn't work for me, I get a 401 error. Authentication error.
> 
> My work around was to pass the user and password on through the url. So this worked for me: `CUSTOM_NTFY_SERVER: 'https://user:password@ntfy.domain.tld'`
> 
> Will continue to check if I can get `NTFY_USER and NTFY_PASS` to work.

I have tried a few times, however I cannot replicate the 401 error with the current code. Are you running a self-hosted NTFY server?

**Comment by Proximus888** [comment]
> 
> 
> 
> > > @Proximus888 @Nairou NTFY is in the latest build. I still plan to add appraise, however I just havent had a chance to do so yet.
> > 
> > Thanks, works.
> > 
> > But `NTFY_USER and NTFY_PASS` doesn't work for me, I get a 401 error. Authentication error.
> > 
> > My work around was to pass the user and password on through the url. So this worked for me: `CUSTOM_NTFY_SERVER: 'https://user:password@ntfy.domain.tld'`
> > 
> > Will continue to check if I can get `NTFY_USER and NTFY_PASS` to work.
> 
> I have tried a few times, however I cannot replicate the 401 error with the current code. Are you running a self-hosted NTFY server?
> 

Yes, I am running a selfhosted NTFY server on a VPS. With on local network running DNS and NGINX reverse proxy.

Local server can revolve and ping custom domain ntfy.domain.tld. Other services work with user and pass (tautulli).

**Comment by petersem** [comment]
@Proximus888 What does your compose look like?

**Comment by Proximus888** [comment]
> @Proximus888 What does your compose look like?
> 
> This works for me:
> 
> ```
>   monocker:
>     container_name: monocker
>     image: petersem/monocker
>     environment:
>       SERVER_LABEL: 'Dev'
>       SERVER_AVATAR: 'https://content.invisioncic.com/u329766/monthly_2024_05/monocker.png.ba5ffdb390b627097d2a53645cf87350.png'
>       MESSAGE_PLATFORM: 'ntfy@testing'
>       LABEL_ENABLE: 'false'
>       ONLY_OFFLINE_STATES: 'false'
>       EXCLUDE_EXITED: 'false'      
>       PERIOD: 30
>       DISABLE_STARTUP_MSG: 'false'
> 
>       ## ADVANCED NTFY SETTINGS
>       CUSTOM_NTFY_SERVER: 'https://ntfy.mydomain.net' 
>       NTFY_USER: 'my_user_id' 
>       NTFY_PASS: 'my_password' 
>     volumes:
>       - /var/run/docker.sock:/var/run/docker.sock:ro
>     restart: unless-stopped
> ```

This one doesn't work for me:
```
  monocker:
    container_name: monocker
    image: petersem/monocker
    environment:
      SERVER_LABEL: 'NUC1'
      MESSAGE_PLATFORM: 'ntfy@monocker'
      CUSTOM_NTFY_SERVER: 'https://ntfy.domain.tld'
      NTFY_USER: 'sensitive'
      NTFY_PASS: 'sensitive'
      LABEL_ENABLE: 'false'
      ONLY_OFFLINE_STATES: 'false'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - utility
    restart: unless-stopped
```

Then I get:
```
-------------------------------------------------------
 Monocker - MONitor dOCKER container states
 Developed by Matt Petersen - Brisbane Australia
 
 Version: 2.10.1
-------------------------------------------------------
 
Monitoring started 
     - Version: 2.10.1
     - Messaging platform: ntfy
     - Polling period: 10 seconds 
     - Only offline state monitoring: false
     - Only include labelled containers: false 
     - Do not monitor 'Exited': false
     - Disable Startup Messages: false
     - Display SHA ID: false

     - Currently monitoring 27 (running) containers
Request failed with status code 401
Request failed with status code 401
    - monocker: running (healthy)
*****monocker: running (healthy)
Request failed with status code 401
```

But this one works for me:

```
  monocker:
    container_name: monocker
    image: petersem/monocker
    environment:
      SERVER_LABEL: 'NUC'1
      MESSAGE_PLATFORM: 'ntfy@monocker'
      CUSTOM_NTFY_SERVER: 'https://user:password@ntfy.domain.tld'
      LABEL_ENABLE: 'false'
      ONLY_OFFLINE_STATES: 'false'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - utility
    restart: unless-stopped
```


My ntfy user password contains symbols, I don't know if that is throwing something off.
