### ISSUE TITLE
Multiple Hosts?

### ISSUE THREAD

**Issue by Its4Nik** [petersem/monocker#93]
Is it possible to use more then one host as a monitoring endpoint?

Like with [dozzle](https://github.com/amir20/dozzle) you can add more then one host to see logs.
And I would like to ask if this is also possible with monocker.

This would be a dozzle configuration for example:
```yaml
dozzle:
    restart: always
    image: amir20/dozzle:latest
    labels:
      autoheal-app: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    container_name: dozzle
    ports:
      - 8989:8080
    environment:
      DOZZLE_ENABLE_ACTIONS: true
      DOZZLE_HOSTNAME: Fin-1
      DOZZLE_REMOTE_HOST: tcp://10.0.0.3:2375|Fin-2,tcp://10.0.0.4:2375|Fin-3
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
```

As you can see there are multiple Hosts at the DOZZLE_REMOTE_HOST part.
